sudo: required
dist: xenial
group: edge
language: node_js
cache:
  yarn: true
  directories:
  - node_modules
services:
- docker
node_js:
- '6'

before_install:
- sudo rm /usr/local/bin/docker-compose
- sudo pip install docker-compose
- docker-compose -v
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
- export PATH=$HOME/.yarn/bin:$PATH
install:
- tar xvjf build/var_lib_ldap.tbz2 -C build/
- tar xvjf build/etc_ldap_slapd.d.tbz2 -C build/
- docker-compose -f build/docker-compose.yml up -d
- cp -v app/conf.example.js app/conf.js
- cp -v tests/conf.example.js tests/conf.js
- yarn global add gulp
- yarn
- node build/store.js
branches:
  only:
  - master
  - production
after_success:
- echo $DOCKER_USERNAME
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- export REPO="openmrsinfra/id"
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build . -t $REPO:$TAG
- docker tag $REPO:$TAG $REPO:"staging"
- docker push $REPO
notifications:
  email: true
