version: "2.1"

services:
  web:
    user: "${UID-1000}:${GID-1000}"
    env_file: .env.development
    build:
      context: .
    ports:
      - 0.0.0.0:3000:3000
    depends_on:
      mailcatcher:
        condition: service_started
      mongodb:
        condition: service_healthy
      openldap:
        condition: service_started
    volumes:
      - .:/opt/id
    restart: unless-stopped
  mongodb:
    image: mongo:3.4
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - ./data/mongo/db:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "localhost/test", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 1)';"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    command: "mongod --nojournal --smallfiles"
  mailcatcher:
    image: jeanberu/mailcatcher
    ports:
      - "0.0.0.0:1080:1080"
      - "0.0.0.0:1025:1025"
    restart: unless-stopped
  openldap:
    image: osixia/openldap:1.1.8
    environment:
      - LDAP_TLS=false
    volumes:
      - ./data/ldap/etc/ldap/slapd.d:/etc/ldap/slapd.d
      - ./data/ldap/var/lib/ldap:/var/lib/ldap
    restart: unless-stopped
    ports:
      - 127.0.0.1:389:389
