sudo: false
dist: trusty
language: node_js
cache:
  yarn: true
  directories:
    - node_modules


node_js:
  - "6"
env:


install:
  - npm install -g mocha
  - npm install

branches:
  only:
    - master

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#openmrs"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    use_notice: true
    skip_join: true

script:
  - npm test
